metadata:
  acknowledgement: This study used data collected and made freely available by Voice of the Ocean Foundation 
                   (https://www.voiceoftheocean.org) accessed from https://erddap.voiceoftheocean.org
  comment: <Any other relevant info. Fine to leave blank>
  contributor_name: Callum Rollo, <PI name>, <glider techinician name>
  contributor_role: Data Processor, Principal Investigator, Glider Technician
  creator_email: <your email>
  creator_name: <your name>
  creator_url: <your website>
  deployment_id: <mission number>
  deployment_name: <mission name>
  # date format 'yyyy-mm-dd'
  deployment_start: <start date>
  deployment_end: <end date (approx)>
  format_version: IOOS_Glider_NetCDF_v2.0.nc
  glider_name: <glider name>
  glider_serial: <glider number>
  glider_model: SeaExplorer
  glider_instrument_name: seaexplorer
  wmoid: <glider wmo>
  institution: Voice of the Ocean Foundation
  keywords: "AUVS, Autonomous Underwater Vehicles, Oceans, Ocean Pressure,
             Water Pressure, Ocean Temperature, Water Temperature,
             Salinity/Density, Conductivity, Density, Salinity"
  keywords_vocabulary: GCMD Science Keywords
  license: Creative Commons Attribution 4.0 (https://creativecommons.org/licenses/by/4.0/)
           This study used data collected and made freely available by Voice of the Ocean Foundation
           (https://www.voiceoftheocean.org) accessed from https://erddap.voiceoftheocean.org
  metadata_link: <metadata link>
  Metadata_Conventions: CF-1.6, Unidata Dataset Discovery v1.0
  naming_authority: Voice of the Ocean Foundation
  platform_type:    "SeaExplorer Glider"
  processing_level: "Data provided as is with no expressed or implied
                     assurance of quality assurance or quality control. L0"
  project: <project name>
  project_url: <project url>
  publisher_email: callum.rollo@voiceoftheocean.org
  publisher_name:  Callum Rollo
  publisher_url:   https://voiceoftheocean.org
  references:     "created with pyglider https://github.com/c-proof/pyglider"
  # Examples: Skagerrak, Kattegatt, Baltic, Gulf of Bothnia, Gulf of Finland, Gulf of Riga
  sea_name: <sea name e.g. Baltic>
  source:     Observational data from a profiling glider.
  standard_name_vocabulary: CF STandard Name Table v49
  summary: <mission summary>
  transmission_system: IRIDIUM
  wmo_id: <glider wmo>
  transmission_system: IRRIDIUM
